### PR TITLE
Small style fix

### PR DESCRIPTION
**Pull request by david-prv**
- fixed input fields (in modals, logins, etc) [NOT in forum!]
- adds my close button proposal

### CODE REVIEW

**Comment by ColinTimBarndt** [comment]
What exactly does this PR fix? Can you show a screenshot of the before/after?

**Comment by david-prv** [comment]
input fields, pagination and close button of modals:
before they had a white background and standard border. Also the close button had seemingly buggy color (see [my comment](https://github.com/ColinTimBarndt/stylus_cms-sic-saarland-theme/commit/d59aa9be53e93eb6d63331660e2ef4bca329e577#r64346558)).
image
image
image
image

**Comment by david-prv** [comment]
and also fixes this alignment

image

**Comment by ColinTimBarndt** [comment]
Input fields were already fixed for the event view. I generalized the style to fit all text/password input elements such that they look equal to the input fields on the Prog1 forum.
image

You're right, the close button needs to be properly styled. I might have overlooked something, but I can't see which button alignment would be fixed as it looks like there's no difference to the current style:

image

**Comment by david-prv** [comment]
If you removed the display flex already due to my issue request, you already fixed it on your site. I proposed this PR when you did not fix it yet. But the close button is still a thing:)

**Comment by ColinTimBarndt** [comment]
Sorry for the delay, I was very busy with university. This has been fixed in 9615dbeccca8480717b58936a055eeed4bc08114.

**Pull request closed without merging**
